name: pip-compile-upgrade

on:
  workflow_call:
    gh-token:
      description: >-
        GitHub token.
      required: true
    title:
      description: >-
        Title for the pull request.
      required: false
      default: ''
    body:
      description: >-
        Body for the pull request.
      required: false
      default: ''
    body-file:
      description: >-
        Read body text from file.
      required: false
      default: ''
    auto-merge:
      description: >-
        Automatically merge only after necessary requirements are met.
      required: false
      default: 'yes'
  workflow_dispatch:
    inputs:
      complied_branch:
        description: "The compiled barnch for PR"
        default: "Update req"
        required: true
        type: string
      pull_request_base_branch:
        description: "Base branch for PR"
        default: "main"
        required: true
        type: string
      pip_compile_input_file:
        type: string
        default: "requirements.in"
        description: "Path of req file"
      pip_compile_output_file:
        type: string
        default: "requirements.txt"
        description: "Path of req.txt file"
jobs:

  check_branch:
    name: Check branch name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Abort if branch exists
        run: |
          if [[-n "$(git ls-remote --heads origin ${{inputs.complied_branch}})"]];then 
          exit 1
          fi
  compile_reqs:
    name: Compile requirements
    runs-on: "windows-latest"
    steps:
      - name : Check outCode
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache : 'pip'
      - name: Install Pyhton Packages
        run: |
          pip install --upgrade pip==23.*
          pip install pip-tools==7.*
      - name: Compile requirements
        shell: bash
        run: |
          pip-compile --no-emit-index-url --no-emit-trusted-host --output-file=${{inputs.pip_compile_output_file}} \
          ${{inputs.pip_compile_input_file}}

#runs:
#  using: composite
#  steps:
#    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
#      shell: bash

      - name: Create Pull Request
        shell: bash
        env:
          GH_TOKEN: ${{ inputs.gh-token }}
          INPUT_TITLE: ${{ inputs.title }}
          INPUT_BODY: ${{ inputs.body }}
          INPUT_BODY_FILE: ${{ inputs.body-file }}
          INPUT_AUTO_MERGE: ${{ inputs.auto-merge }}
        run: |
          create.sh